open-run/backend

.ebextensions, .github/CODEOWNERS, .github/auto-assign.yml, .github/workflows/cicd.yml, Procfile
GitHub Action을 활용한 CI-CD 설정. 
프로젝트 빌드 후 AWS Elastic Beanstalk으로 자동 배포. 
연관된 이슈: BE-7
- `.github/workflows/cicd.yml` 및 기타 관련 파일 추가
=> BE-7, chore: cicd.yml 생성

.gitignore, build.gradle, src/main/resources/application.yml.sample
데이터베이스 관련 의존성 추가 및 설정
연관된 이슈: BE-8
- `build.gradle`: comment 살리기.
- `.gitignore`: secret 정보가 담겨질 `application.yml` 파일에 대한 ignore 추가.
- `application.yml.sample`: 설정해야하는 `application.yml` 파일 샘플 내용.
=> BE-8, feature: connect to RDS

.github/workflows/cicd.yml
과금 이슈로 인해 환경 재설정
연관된 이슈: [BE-12](https://open-run.atlassian.net/browse/BE-12)
cicd.yml에 환경명 변경
[BE-12]: https://open-run.atlassian.net/browse/BE-12?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BE-12: beanstalk 환경 변경

.github/workflows/cicd.yml
연관된 이슈: BE-12
서버를 준형이가 세팅해놓은 aws beanstalk로 변경
=> BE-12: change AWS server

.github/auto_assign.yml, build.gradle, src/main/resources/application.yml.sample, src/main/resources/schema.sql
AWS 과금을 유도하는 postgres를 버리고 mysql로 갈아타기
연관된 이슈: BE-12
=> BE-12: DB 변경

.ebextensions/00-makeFiles.config, Procfile
=> BE-12: fix deploy

src/main/java/io/openur/domain/user/dto/GetUserResponseDto.java, src/main/java/io/openur/domain/user/entity/UserEntity.java, src/main/java/io/openur/domain/user/model/User.java, src/main/java/io/openur/domain/user/repository/UserRepositoryImpl.java, src/main/java/io/openur/domain/user/service/UserService.java
=> BE-16 fix build error

.github/workflows/cicd.yml, src/main/resources/application.properties
=> BE-19, feature: inject secret config data while ci-cd

src/main/resources/application.properties, src/main/resources/application.yml.sample
redirect-uri 값이 배포된 서버의 ip로 변경되어야 함.
해당 ip 값은 공개되선 안되므로 시크릿 값으로 추가함.
연관된 이슈: BE-15
=> BE-20, fix: oauth client redirect-uri host value

src/main/java/io/openur/domain/user/controller/UserController.java, src/main/java/io/openur/domain/user/dto/GetUsersLoginDto.java, src/main/java/io/openur/domain/user/dto/PatchUserSurveyRequestDto.java, src/main/java/io/openur/domain/user/entity/UserEntity.java, src/main/java/io/openur/domain/user/model/User.java, src/main/java/io/openur/domain/user/repository/UserRepository.java, src/main/java/io/openur/domain/user/repository/UserRepositoryImpl.java, src/main/java/io/openur/domain/user/service/UserService.java, src/main/resources/schema.sql
설문조사(닉네임, 러닝빈도, 러닝페이스) 정보 저장 api 구현.
연관된 이슈: BE-17
+ 64a2bfdb4ec91b3178e69060d39a5ff86146fdf2 : User에 러닝빈도, 러닝페이스 column 추가.
+ 46183bd9b01b7004c9b79bda4b9f73d49c17e6d5 : 설문조사 정보 저장 api 구현.
+ 653987cd844fca25eac4c8ce8eba6341da63e433 : 오타 수정
+ 77c7a2ab0a431ce180ae7de2806d047877fc2df1 : 업데이트 시 null은 업데이트되지 않도록 수정
=> 설문조사 결과 저장 endpoint 구현

src/main/java/io/openur/domain/user/dto/GetUserResponseDto.java, src/main/java/io/openur/domain/user/dto/PatchUserSurveyRequestDto.java, src/main/java/io/openur/domain/user/entity/UserEntity.java, src/main/java/io/openur/domain/user/model/User.java, src/main/resources/schema.sql
=> BE-17, fix: typo

src/main/java/io/openur/domain/user/service/oauth/KakaoService.java, src/main/java/io/openur/domain/user/service/oauth/NaverService.java
네이버 로그인 405 에러 픽스
연관된 이슈: BE-23
간단하여 생략.
=> BE-23, fix: fix naver login service

build.gradle, src/main/java/io/openur/domain/user/controller/UserController.java, src/main/java/io/openur/domain/user/service/UserService.java, src/main/java/io/openur/global/Filter/JwtAuthenticationFilter.java, src/main/java/io/openur/global/config/SecurityConfig.java, src/main/java/io/openur/global/config/SwaggerAuthConfig.java, src/main/java/io/openur/global/config/SwaggerConfig.java, src/main/java/io/openur/global/dto/ExceptionDto.java, src/main/java/io/openur/global/security/UserDetailsImpl.java, src/main/java/io/openur/global/security/UserDetailsServiceImpl.java
Add filter and swagger,security config
Add filter and swagger,security config
=> BE-19 Add filter and swagger,security config

src/main/resources/application.properties, src/main/resources/application.yml.sample
LoginService error due to redirect URI mismatch.
** 배포 전 주의 ** : `application.yml` 값 업데이트 필요.
연관된 이슈: BE-27
=> BE-27, fix: modify redirect-uri to frontend's uri value

src/main/java/io/openur/global/interceptor/LogInterceptor.java
제곧내
연관된 이슈: BE-29
- `LogInterceptor` 에 조건 추가
=> `/health` 200 로그는 안 찍히게 처리하기

src/main/java/io/openur/domain/user/controller/UserController.java, src/main/java/io/openur/domain/user/service/UserService.java
=> fix reversed condition check bug in `/nickname/exist`

build.gradle, src/main/java/io/openur/domain/user/controller/UserController.java, src/main/java/io/openur/global/config/WebConfig.java, src/test/java/io/openur/config/TestSupport.java, src/test/java/io/openur/controller/BungControllerTest.java, src/test/java/io/openur/controller/UserBungControllerTest.java, src/test/java/io/openur/controller/UserControllerTest.java, src/test/java/io/openur/controller/WithdrawController.java, src/test/resources/application-test.properties, src/test/resources/data.sql
localhost:3000, Swagger UI 에서 발생하는 CORS 문제 해결
: preflight 사용 http method 는 "OPTION" 임
test code 추가
: h2 파일 형식 DB 사용, 현재 만들어진 UserController 단 추가
+ 향후 테스트 db 변동 내역으로 test 가 실패할 것을 대비해, controller 별로 초기화 하는 것 고려
연관된 이슈: NaN
CORS : allowed method 에 OPTION 추가
=> fix cors, add test configuration, steps

src/main/java/io/openur/global/config/WebConfig.java
OPTION 이 아니라 OPTIONS 인데 빠뜨림
'S'
- [V] 버그 수정
- [V] 테스트를 통과했나요?
- [V] 컴파일 가능한가요?
- [V] PR 하기 전에 코드를 다시 한번 살펴보셨나요?
=> BE-30, fix: typo missing 'S'

src/main/java/io/openur/global/Filter/JwtAuthenticationFilter.java
`JwtAuthenticationFilter`에서 jwt handling을 자체적으로 다시 하면서 key null 에러 발생. 어차피 이미 관련 핸들링을 잘 해둔 `JwtUtil`을 활용하도록 변경한다. 
연관된 이슈: [BE-31](https://open-run.atlassian.net/browse/BE-31)
- `JwtUtil`에 이미 구현되어 있는 로직은 해당 구현체 사용하도록 변경.
- invalid 토큰 응답 핸들링 400 -> 401로 변경.
[BE-31]: https://open-run.atlassian.net/browse/BE-31?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BE-31, fix: jwt token handling error

build.gradle, src/main/java/io/openur/global/config/SwaggerConfig.java, src/test/java/io/openur/ApplicationTests.java, src/test/java/io/openur/config/TestSupport.java, src/test/java/io/openur/controller/UserControllerTest.java, src/test/resources/application-test.properties, src/test/resources/data.sql
Swagger : 도메인이 https 인데 반해 Swagger UI 에서 http 로 내부서버 호출을 했기 때문에 CORS 문제가 있었던것으로 보임
H2 Test DataBase : test data base 생성 이후 정상적으로 drop 되지 않는 문제, 사용 버전과 파일 에러
Swagger : Auth, Unauth 각각의 탭에서 도메인을 선택하는 란에서 올바른 도메인을 선택해주어야함
=> fix : data h2, swagger errors

src/main/java/io/openur/domain/user/dto/GetUserResponseDto.java, src/main/java/io/openur/domain/user/entity/UserEntity.java, src/main/java/io/openur/domain/user/model/User.java, src/main/java/io/openur/domain/withdraw/controller/WithdrawController.java, src/main/java/io/openur/domain/withdraw/entity/WithdrawEntity.java, src/main/java/io/openur/domain/withdraw/model/Withdraw.java, src/main/java/io/openur/domain/withdraw/repository/WithdrawJpaRepository.java, src/main/java/io/openur/domain/withdraw/repository/WithdrawRepository.java, src/main/java/io/openur/domain/withdraw/repository/WithdrawRepositoryImpl.java, src/main/java/io/openur/domain/withdraw/service/WithdrawService.java, src/main/resources/schema.sql, src/test/java/io/openur/controller/WithdrawController.java, src/test/resources/data.sql
연관된 이슈: #46 
Modification related to immediate deletion of withdrawn member data (not used)
=> BE-35, Refactor: Modification related to immediate deletion of withdrawn member data (not used)

src/main/java/io/openur/domain/user/controller/UserController.java, src/main/java/io/openur/domain/user/dto/GetUserResponseDto.java, src/main/java/io/openur/domain/user/repository/UserRepository.java, src/main/java/io/openur/domain/user/repository/UserRepositoryImpl.java, src/main/java/io/openur/domain/user/service/UserService.java, src/test/resources/data.sql
JsonFormatter for LocalDateTime as json string
UserEntity Deletion
- Formatted as : "yyyy-MM-dd HH:mm:ss"
- 해외 사용자가 있다면 timezone 고려도 필요
- 유저 벙 엔티티가 구상되어있지 않아서, 해당 유저 탈퇴시 유저-벙 테이블 내 데이터 삭제까지 구현은 못했음
- 엔티티 구상 끝나면 추가토록 하겠습니다.
=> BE-33, JsonFormatter and UserEntity deletion

src/main/resources/schema.sql
bung 테이블명 변경
연관된 이슈: #36
+ 32c60a0: bung 테이블명 변경
+ da5fdcf : bung description의 Not Null 변경
+ 556a93d : hashtag 테이블 추가
+ 533b6f5 : 오타 수정
before:
- tb_bung
- tb_users_bung
after:
- tb_bungs
- tb_users_bungs
=> BE-36, chore: edit bung table name

src/test/resources/data.sql
변경된 스키마와 test data.sql 동기화
/test/data.sql 
- [V] 문서 업데이트
- [V] 테스트를 통과했나요?
- [V] 컴파일 가능한가요?
- [V] PR 하기 전에 코드를 다시 한번 살펴보셨나요?
=> BE-37, test: data.sql for test sync with schema

src/main/java/io/openur/global/config/WebConfig.java
HTTP - DELETE 에 대한 CORS 허용
상기와 동일
=> BE-33, fix: CORS allow for method "DELETE"

src/main/java/io/openur/domain/bung/controller/BungController.java, src/main/java/io/openur/domain/bung/dto/BungDetailDto.java, src/main/java/io/openur/domain/bung/dto/GetBungDetailDto.java, src/main/java/io/openur/domain/bung/dto/PostBungEntityDto.java, src/main/java/io/openur/domain/bung/entity/BungEntity.java, src/main/java/io/openur/domain/bung/model/Bung.java, src/main/java/io/openur/domain/bung/repository/BungJpaRepository.java, src/main/java/io/openur/domain/bung/repository/BungRepository.java, src/main/java/io/openur/domain/bung/repository/BungRepositoryImpl.java, src/main/java/io/openur/domain/bung/service/BungService.java, src/main/java/io/openur/domain/user/controller/UserController.java, src/main/java/io/openur/domain/user/dto/GetUserResponseDto.java, src/main/java/io/openur/domain/user/dto/GetUsersLoginDto.java, src/main/java/io/openur/domain/user/model/User.java, src/main/java/io/openur/domain/user/repository/UserJpaRepository.java, src/main/java/io/openur/domain/user/repository/UserRepository.java, src/main/java/io/openur/domain/user/repository/UserRepositoryImpl.java, src/main/java/io/openur/domain/user/service/UserService.java, src/main/java/io/openur/domain/user/service/oauth/LoginService.java, src/main/java/io/openur/domain/userbung/entity/UserBungEntity.java, src/main/java/io/openur/domain/userbung/model/UserBung.java, src/main/java/io/openur/domain/userbung/repository/UserBungJpaRepository.java, src/main/java/io/openur/domain/userbung/repository/UserBungRepository.java, src/main/java/io/openur/domain/userbung/repository/UserBungRepositoryImpl.java, src/main/java/io/openur/global/common/UtilController.java, src/main/java/io/openur/global/security/UserDetailsImpl.java, src/main/java/io/openur/global/security/UserDetailsServiceImpl.java, src/test/java/io/openur/controller/BungControllerTest.java, src/test/java/io/openur/controller/UserBungControllerTest.java, src/test/resources/data.sql
- User_Bung & Bung repository, entity, etc
- Bung Post & Get API added
- Test function of Bung POST add
- Test function of Bung GET need discussion : paging, single, what to get
=> BE-37, Bung Post-Create, Get-Detail

src/main/java/io/openur/domain/bung/controller/BungController.java, src/main/java/io/openur/domain/bung/repository/BungRepository.java, src/main/java/io/openur/domain/bung/repository/BungRepositoryImpl.java, src/main/java/io/openur/domain/bung/service/BungService.java, src/main/java/io/openur/domain/user/service/oauth/LoginService.java, src/main/java/io/openur/domain/userbung/entity/UserBungEntity.java, src/main/java/io/openur/domain/userbung/model/UserBung.java, src/main/java/io/openur/domain/userbung/repository/UserBungJpaRepository.java, src/main/java/io/openur/domain/userbung/repository/UserBungRepository.java, src/main/java/io/openur/domain/userbung/repository/UserBungRepositoryImpl.java, src/main/resources/schema.sql, src/test/resources/data.sql
벙주 권한과 관련된 기능들 추가.
그 외에는 기 PR 에서 미처 발견하지 못한 부분들 리팩토링.
연관된 이슈: BE-39
- 9d6ae7e14a4390591428b0a250ce951c0ea0bedc: `isOwner` column 추가
- 25b008b8f4940931fc3a7a258ff23bd9fd598fb1: 추후 벙주 권한 제한을 하기 위해 필요할 `isOwnerOfBung` 추가
- 20a5df2e5cbfafa0ab903c7a4d6817a3222c7e50: missing @AuthenticationPrincipal. 사실 AuthenticationPrincipal의 정확한 동작 방식을 몰라서 꼭 필요한건진 모르겠음. 검토 필요
- a7baad5e77ed1718560c28e7ffb5e82c5dd33ecb: use BungEntity and UserBungEntity only at lowest level. UserEntity만 수정하고 나머지를 수정 안함.
=> BE-39: add `isOwner` data related functions

src/main/java/io/openur/domain/bung/controller/BungController.java, src/main/java/io/openur/domain/bung/service/BungService.java, src/main/java/io/openur/domain/userbung/model/UserBung.java, src/main/java/io/openur/domain/userbung/repository/UserBungJpaRepository.java, src/main/java/io/openur/domain/userbung/repository/UserBungRepository.java, src/main/java/io/openur/domain/userbung/repository/UserBungRepositoryImpl.java, src/main/java/io/openur/global/exception/ExceptionController.java
벙주 변경 기능 추가.
(기존 벙주와 바뀌는 벙주 모두 동의한 상태)
연관된 이슈: BE-40
3f87c25 : 벙주 변경 기능 추가
bd5e794 : @PreAuthorize annotation 추가
5e887e0 : @PreAuthorize annotation 내용 추가 수정
=> BE-40: Added function to change Bung owner

src/test/java/io/openur/config/TestSupport.java, src/test/java/io/openur/controller/BungApiTest.java, src/test/java/io/openur/controller/BungControllerTest.java, src/test/java/io/openur/controller/UserApiTest.java, src/test/java/io/openur/controller/UserBungApiTest.java, src/test/java/io/openur/controller/UserBungControllerTest.java
벙주 변경 테스트코드 추가
연관된 이슈: BE-44
벙주 변경 관련 테스트코드 추가
=> BE-44, Add test code to change bung owner

.github/java_format.yml, docker-compose.yml
=> Misc: docker-compose for DB & enforce java formatter on push, PR

src/main/java/io/openur/domain/bung/controller/BungController.java, src/main/java/io/openur/domain/bung/service/BungService.java, src/main/java/io/openur/domain/userbung/repository/UserBungJpaRepository.java, src/main/java/io/openur/domain/userbung/repository/UserBungRepository.java, src/main/java/io/openur/domain/userbung/repository/UserBungRepositoryImpl.java, src/main/java/io/openur/domain/userbung/service/UserBungService.java, src/test/java/io/openur/controller/BungApiTest.java
멤버 삭제 (강퇴) endpoint 추가
연관된 이슈: #BE-42
멤버 삭제 (강퇴) endpoint 추가 및 테스트 코드 추가
(api 테스트 시, 500 return)
=> BE-42 feature : 멤버 삭제 (강퇴) endpoint 추가

src/main/java/io/openur/domain/bung/controller/BungController.java, src/main/java/io/openur/domain/bung/repository/BungJpaRepository.java, src/main/java/io/openur/domain/bung/repository/BungRepository.java, src/main/java/io/openur/domain/bung/repository/BungRepositoryImpl.java, src/main/java/io/openur/domain/bung/service/BungService.java, src/main/java/io/openur/global/config/SecurityConfig.java, src/main/resources/schema.sql, src/test/java/io/openur/config/TestSupport.java, src/test/java/io/openur/controller/BungApiTest.java, src/test/java/io/openur/controller/UserApiTest.java
벙 삭제 기능을 추가한다. 
연관된 이슈: [BE-38](https://open-run.atlassian.net/browse/BE-38)
- 75bce3b741ededfb0c59824b555fa6274b3acbef: 벙 삭제 controller method 추가
- 215c75d156a5f85192d2e382ec841e09a67168a9: 벙 생성 endpoint에 bungId response data 추가 및 관련 테스트 코드 추가 (근데 이거 안하기로 했던거 같기도? 예에엣날에 작업하던거 그대로 끌고온거라서 수정 필요하면 얘기 ㄱㄱ)
- b1b18d1eef3c08521d04886db4efde323be93e1f: 벙 삭제 테스트 코드 추가 (403 테스트 에러남)
- ad06e4ec7faff20ac75e8c5952af8f5bd563b91a: 403 케이스 테스트 에러 수정 - mockMvc에 springSecurity 적용
[BE-38]: https://open-run.atlassian.net/browse/BE-38?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BE-38] 벙 삭제 endpoint 추가

src/main/java/io/openur/domain/bung/controller/BungController.java, src/test/java/io/openur/controller/BungApiTest.java
경로 이름 수정: member -> members
연관된 이슈: BE-47
=> BE-47, fix: `/v1/bungs/{bung-id}/members/{user-id}` path name

build.gradle, src/main/java/io/openur/domain/bung/controller/BungController.java, src/main/java/io/openur/domain/bung/dto/Req/InviteMembersRequestDto.java, src/main/java/io/openur/domain/bung/entity/BungEntity.java, src/main/java/io/openur/domain/bung/repository/BungRepositoryImpl.java, src/main/java/io/openur/domain/bung/repository/dao/BungDAO.java, src/main/java/io/openur/domain/bung/service/BungService.java, src/main/java/io/openur/domain/user/controller/UserController.java, src/main/java/io/openur/domain/user/dto/GetSelfResponseDto.java, src/main/java/io/openur/domain/user/dto/GetUsersResponseDto.java, src/main/java/io/openur/domain/user/repository/UserJpaRepository.java, src/main/java/io/openur/domain/user/repository/UserRepositoryImpl.java, src/main/java/io/openur/domain/user/service/UserService.java, src/main/java/io/openur/domain/userbung/repository/UserBungRepositoryImpl.java, src/main/java/io/openur/domain/userbung/repository/dao/UserBungDAO.java, src/main/java/io/openur/global/common/PagedResponse.java, src/main/java/io/openur/global/common/Response.java, src/main/java/io/openur/global/config/QueryDslConfig.java, src/main/java/io/openur/global/enums/BungStatus.java, src/test/java/io/openur/controller/BungApiTest.java, src/test/java/io/openur/controller/UserApiTest.java, src/test/resources/data.sql
Query Dsl Setting
Response DTO with Pagination
Bung API 
- GET : /bungs
- POST : /bungs/invitation
Users API 
- GET : /users/suggestion
( 상과 동 )
isOwnerBung 및 예진 누나의 테스트 코드 버그 픽스 사항이 적용되어야 test 가 될 것으로 보임
해당 코드 서로 병합 필요
- [v] 버그 수정
- [v] 새로운 기능
- [v] 대규모 변경
=> BE-51, Query Dsl 외 4개

src/main/java/io/openur/domain/bung/controller/BungController.java, src/main/java/io/openur/domain/bung/dto/BungDetailDto.java, src/main/java/io/openur/domain/bung/repository/BungJpaRepository.java, src/main/java/io/openur/domain/bung/repository/BungRepositoryImpl.java, src/main/java/io/openur/domain/bung/repository/dao/BungDAO.java, src/main/java/io/openur/domain/bung/service/BungService.java, src/main/java/io/openur/domain/userbung/repository/UserBungJpaRepository.java, src/main/java/io/openur/domain/userbung/repository/UserBungRepository.java, src/main/java/io/openur/domain/userbung/repository/UserBungRepositoryImpl.java, src/main/java/io/openur/domain/userbung/repository/dao/UserBungDAO.java, src/main/java/io/openur/global/enums/BungStatus.java, src/test/java/io/openur/controller/BungApiTest.java, src/test/resources/data.sql
소유한 벙 목록
Order By, 기능을 활용할 것, 꺼내온 엔티티 목록을 DTO 매핑 한후, DTO 내부 데이터로 재 정렬하는 방식은 비효율적
=> BE-46, 소유한 벙 목록

src/main/java/io/openur/domain/xrpl/controller/XrplController.java, src/main/java/io/openur/domain/xrpl/repository/NftUri.java, src/main/java/io/openur/domain/xrpl/repository/XrplRepository.java, src/main/java/io/openur/domain/xrpl/service/XrplService.java, src/main/java/io/openur/global/config/SwaggerConfig.java, src/main/resources/application.yml.sample, src/test/java/io/openur/service/XrplTest.java
NFT minting Endpoint
NFT minting Endpoint
=> feat: NFT minting Endpoint

src/test/resources/application-test.properties
=> fix: add test application property

src/main/java/io/openur/domain/bung/repository/BungRepositoryImpl.java, src/main/java/io/openur/domain/userbung/repository/UserBungRepositoryImpl.java, src/main/java/io/openur/global/enums/BungStatus.java
=> BE-51, fix: get Bung list for pending and achieved

src/main/java/io/openur/domain/xrpl/repository/XrplRepository.java
=> fix Nft Data

src/main/java/io/openur/domain/bung/service/BungService.java, src/main/java/io/openur/domain/userbung/repository/UserBungRepositoryImpl.java, src/main/java/io/openur/domain/userbung/repository/dao/UserBungDAO.java
=> BE-51, fix : get Bung List Logical Error fix

src/main/java/io/openur/domain/xrpl/dto/NftDataDto.java, src/main/java/io/openur/domain/xrpl/repository/Taxon.java, src/main/java/io/openur/domain/xrpl/repository/XrplRepository.java
=> xrpl, refactor

src/main/resources/schema.sql
tb_users_challenges, tb_challenges 테이블 추가
연관된 이슈: #{{BE-56}}
{{tb_users_challenges, tb_challenges 테이블 추가}}
=> BE-56 : 도전과제 DB 설계 tb_users_challenges, tb_challenges 테이블 추가

.github/auto_assign.yml, src/main/java/io/openur/domain/bunghashtag/repository/BungHashtagRepositoryImpl.java
제곧내. #79 머지가 이거땜에 테스트 실패해서 git action 통과 못함. 이것이 테스트 코드의 필요성!
연관된 이슈: BE-54
=> BE-54, fix: persistence works only on JPA entities

src/main/java/io/openur/domain/user/controller/UserController.java, src/main/java/io/openur/domain/user/repository/UserJpaRepository.java, src/main/java/io/openur/domain/user/repository/UserRepository.java, src/main/java/io/openur/domain/user/repository/UserRepositoryImpl.java, src/main/java/io/openur/domain/user/service/UserService.java, src/main/java/io/openur/global/exception/ExceptionController.java, src/main/java/io/openur/global/jwt/JwtUtil.java, src/test/java/io/openur/controller/UserApiTest.java
=> [BE-60] User Nickname 을 통한 검색 메소드

src/main/java/io/openur/domain/bung/controller/BungController.java, src/main/java/io/openur/domain/bung/dto/BungInfoDto.java, src/main/java/io/openur/domain/bung/dto/JoinBungResultDto.java, src/main/java/io/openur/domain/bung/exception/JoinBungException.java, src/main/java/io/openur/domain/bung/model/Bung.java, src/main/java/io/openur/domain/bung/repository/BungJpaRepository.java, src/main/java/io/openur/domain/bung/repository/BungRepository.java, src/main/java/io/openur/domain/bung/repository/BungRepositoryImpl.java, src/main/java/io/openur/domain/bung/service/BungService.java, src/main/java/io/openur/domain/user/controller/UserController.java, src/main/java/io/openur/domain/userbung/controller/UserBungController.java, src/main/java/io/openur/domain/userbung/model/UserBung.java, src/main/java/io/openur/global/dto/ExceptionDto.java, src/main/java/io/openur/global/exception/ExceptionController.java, src/main/resources/schema.sql, src/test/java/io/openur/controller/BungApiTest.java, src/test/java/io/openur/controller/UserBungApiTest.java, src/test/resources/data.sql
연관된 이슈: [BE-63](https://open-run.atlassian.net/browse/BE-63)
- [eb198d7](https://github.com/open-run/backend/pull/89/commits/eb198d7c37cd53ba5566d7a01566db3230515a71), [3fb164e](https://github.com/open-run/backend/pull/89/commits/3fb164e852ce43cc0807e6c3fd8b972690a4e68c): 사소한 설명 추가 및 밀려있던 todo 처리
- [00fe788](https://github.com/open-run/backend/pull/89/commits/00fe7889e7a6336c484dcf91a100e399718d618d): endpoint 정의 (`schema.sql` 에 코멘트 논의 필요)
- [c2a82ec](https://github.com/open-run/backend/pull/89/commits/c2a82ec3cbeb2c8d5a97fae61f8fb7d470cdcf7a): 서비스 구현 (`Bung` constructor 코드라인이 너무 중복됨. 다른 좋은 방법 없을까?)
- [7b4a828](https://github.com/open-run/backend/pull/89/commits/7b4a828a42b5de4ed1f505e04eecf4b4e952c635): 테스트 코드 추가
- [a9ade69](https://github.com/open-run/backend/pull/89/commits/a9ade690a220 …
=> [BE-63] 일반 유저의 벙 참가하기 endpoint 구현 

src/main/java/io/openur/domain/bung/controller/BungController.java, src/main/java/io/openur/domain/bung/dto/BungInfoDto.java, src/main/java/io/openur/domain/bung/dto/BungInfoWithOwnershipDto.java, src/main/java/io/openur/domain/bung/entity/BungEntity.java, src/main/java/io/openur/domain/bung/exception/CompleteBungException.java, src/main/java/io/openur/domain/bung/model/Bung.java, src/main/java/io/openur/domain/bung/repository/BungRepository.java, src/main/java/io/openur/domain/bung/repository/BungRepositoryImpl.java, src/main/java/io/openur/domain/bung/service/BungService.java, src/main/java/io/openur/domain/userbung/repository/UserBungRepository.java, src/main/java/io/openur/domain/userbung/repository/UserBungRepositoryImpl.java, src/main/java/io/openur/global/enums/CompleteBungResultEnum.java, src/main/java/io/openur/global/enums/JoinBungResultEnum.java, src/main/java/io/openur/global/exception/ExceptionController.java, src/main/resources/schema.sql, src/test/java/io/openur/controller/BungApiTest.java, src/test/resources/data.sql
- 제목은 곧 내용
- 죽은자의 소생
연관된 이슈: #92 
암튼 그럼, 제목과 같음
=> BE-65, (BE-68) MyBungs Sorting Issues and CompleteBung Feature

src/main/java/io/openur/domain/user/controller/UserController.java
(api mapping incorrect)
연관된 이슈: #{{BE-74}}
GetMapping -> PatchMapping
=> BE-74, fix: feedback api CORS issue

src/main/java/io/openur/domain/user/controller/UserController.java, src/main/java/io/openur/domain/userbung/controller/UserBungController.java, src/main/java/io/openur/domain/userbung/model/UserBung.java, src/main/java/io/openur/domain/userbung/repository/UserBungJpaRepository.java, src/main/java/io/openur/domain/userbung/repository/UserBungRepository.java, src/main/java/io/openur/domain/userbung/repository/UserBungRepositoryImpl.java, src/main/java/io/openur/domain/userbung/service/UserBungService.java, src/main/java/io/openur/global/security/MethodSecurityService.java, src/test/java/io/openur/controller/UserBungApiTest.java
제곧내.
커밋 순 리뷰 시 용이할걸?
`UserBung.participationStatus` 를 true 로 업데이트 하는 것이 뽀인트
=> [BE-75] 벙 참가 인증 엔드포인트 구현

.gitignore, build.gradle, src/main/java/io/openur/domain/bung/dto/BungInfoDto.java, src/main/java/io/openur/domain/bung/dto/CreateBungDto.java, src/main/java/io/openur/domain/bung/dto/EditBungDto.java, src/main/java/io/openur/domain/bung/entity/BungEntity.java, src/main/java/io/openur/domain/bung/model/Bung.java, src/main/resources/schema.sql, src/test/java/io/openur/controller/BungApiTest.java, src/test/resources/data.sql
BE-77, 이미지 필드
- data.sql, schema.sql
- bung entity
=> [BE-77] 벙 이미지 필드 및 DB 라인 추가

src/main/java/io/openur/domain/user/controller/UserController.java, src/main/java/io/openur/domain/user/dto/GetFeedbackDto.java, src/main/java/io/openur/domain/user/service/UserService.java
=> [BE-78] 벙 참가자 피드백 endpoint 제한 설정

src/main/java/io/openur/domain/challenge/entity/ChallengeEntity.java, src/main/java/io/openur/domain/challenge/event/ChallengeEventsListener.java, src/main/java/io/openur/domain/challenge/event/ChallengeEventsPublisher.java, src/main/java/io/openur/domain/challenge/repository/ChallengeRepositoryImpl.java, src/main/java/io/openur/domain/userchallenge/repository/UserChallengeRepository.java, src/main/java/io/openur/domain/userchallenge/repository/UserChallengeRepositoryImpl.java, src/main/resources/schema.sql
- 루프 내의 반복적인 쿼리 호출 대체
- 도전과제 완료 액션까지 사이클 점검
- Entity 내의 EnumType 정의 수정
- Transform 메소드 사용을 통한 간결화
곧 내
=> BE-00, 도전과제 완료까지 사이클 점검 및 수정

src/main/java/io/openur/domain/bung/dto/BungInfoWithMemberListDto.java, src/main/java/io/openur/domain/bung/repository/BungRepositoryImpl.java, src/main/java/io/openur/domain/userbung/repository/UserBungRepositoryImpl.java
- optimize misconfiguration and prevent N + 1
- 아따 제곧내여
- 그런거여
=> BE-00, hotfix : query errors from DSL

.gitignore, .vscode/java-google-style.xml, .vscode/launch.json, .vscode/settings.json, .vscode/tasks.json, src/test/java/io/openur/controller/NftMetadata.java
연관된 이슈: #BE-89
이미지 폴더 pinata에 업데이트 완료.
소스는 이미지 폴더에 맞게 metadata json 만들어주는 소스.
메타데이터 json 파일도 pinata에 올렸고, 이 올린 메타데이터를 이제 minting 시에 사용하면 됨.
-> 논의점이 몇 가지 있음.
1. attribute 에서 rarity type에 대한 내용.
2. pinata에 올라가있는 폴더에 추가 내용이 있을 경우 처음부터 새로 다시 올려야함. -> 이게 제일 문제인데, 그래서 관리 방법을 몇 가지 생각해봐야 될 것 같음. 
->우선 나는 이미지마다 고유의 이름으로 관리해야 될 것 같음. 그리고 이미지를 하나씩 올리는게 아닌 버전 별로 여러개를 올리면서 관리해야될 것 같음. 
-> 이미지가 용량이 크지 않아서 새로 올리는건 문제되어 보이지는 않지만, 이미지가 늘 수록 다시 새로 올리는 방식은 비효율적인거 같음
=> BE-89, 이미지 생성 및 관리 연구

src/main/resources/schema.sql
tb_bungs 에 새로 추가된 필드 값 schema.sql 에 반영
연관된 이슈: BE-92
=> [BE-92] fix DB schema

src/main/java/io/openur/domain/bung/repository/BungRepositoryImpl.java, src/main/java/io/openur/domain/userbung/repository/UserBungRepositoryImpl.java
Bung 탐색 삼분할 기능 수정
연관된 이슈: #118 BE-92
=> BE-92, fix : select distinct & ordering with out selected field

src/main/java/io/openur/domain/bung/model/Bung.java, src/main/java/io/openur/domain/bung/repository/BungRepositoryImpl.java, src/main/java/io/openur/domain/userbung/repository/UserBungRepositoryImpl.java
변경된 hashtag 로 부터 string 을 꺼내는 것이 아닌 엔티티를 toString 으로 뽑아내고 있는 실수 해결
=> BE-92, Entity to String

src/main/java/io/openur/domain/bung/service/BungService.java, src/main/java/io/openur/domain/challenge/controller/ChallengeController.java, src/main/java/io/openur/domain/challenge/dto/ChallengeInfoDto.java, src/main/java/io/openur/domain/challenge/service/ChallengeService.java, src/main/java/io/openur/domain/userchallenge/repository/UserChallengeRepository.java, src/main/java/io/openur/domain/userchallenge/repository/UserChallengeRepositoryImpl.java, src/test/java/io/openur/controller/ChallengeApiTest.java
=> BE-87, 도전과제 일반과 완료된 과제에 한한 엔드포인트 추가

src/test/java/io/openur/controller/ChallengeApiTest.java
=> BE-87, fix : test functions and sync with enpoints

src/main/java/io/openur/global/config/SwaggerConfig.java
스웨거에 Challenges 활성화
연관된 이슈: #124 
스웨거 엔드포인트
=> BE-87, fix: Swagger Config endpoint release
